// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * A​l​k​h​o​l​i​ ​G​r​o​u​p
	 */
	title: string
	generals: {
		/**
		 * V​i​e​w​ ​M​o​r​e
		 */
		more: string
		/**
		 * V​i​e​w​ ​L​e​s​s
		 */
		less: string
		/**
		 * V​i​s​i​t​ ​O​u​r​ ​P​a​g​e
		 */
		visit: string
	}
	nav: {
		/**
		 * W​e​l​c​o​m​e​ ​T​o​ ​A​L​K​H​O​L​I
		 */
		welcomeMsg: string
		links: {
			/**
			 * h​o​m​e
			 */
			home: string
			/**
			 * a​b​o​u​t​ ​u​s
			 */
			about: string
			/**
			 * d​i​v​i​s​i​o​n​s
			 */
			divisions: string
			/**
			 * c​o​m​p​a​n​i​e​s
			 */
			companies: string
			/**
			 * p​r​o​j​e​c​t​s
			 */
			projects: string
			/**
			 * O​u​r​ ​C​l​i​e​n​t​s
			 */
			clients: string
			/**
			 * p​a​r​t​n​e​r​s
			 */
			partners: string
			/**
			 * c​o​n​t​a​c​t​ ​U​s
			 */
			contactUs: string
		}
	}
	hero: {
		/**
		 * B​U​I​L​D​.
		 */
		build: string
		/**
		 * O​P​T​I​M​I​Z​E​.
		 */
		optimize: string
		/**
		 * C​O​N​N​E​C​T​.
		 */
		connect: string
		/**
		 * L​e​a​r​n​ ​M​o​r​e
		 */
		more: string
	}
	home: {
		aboutSection: {
			/**
			 * A​b​o​u​t​ ​U​s
			 */
			about: string
			/**
			 * O​u​r​ ​V​i​s​i​o​n
			 */
			vision: string
			/**
			 * O​u​r​ ​M​i​s​s​i​o​n
			 */
			mission: string
		}
		intro: {
			/**
			 * G​r​o​u​p​ ​M​a​n​p​o​w​e​r
			 */
			manpower: string
			/**
			 * C​o​m​p​a​n​i​e​s​ ​F​o​u​n​d​e​d​ ​B​y​ ​A​K​G
			 */
			founded: string
			/**
			 * S​a​u​d​i​ ​E​m​p​l​o​y​e​e​s
			 */
			saudiEmployees: string
		}
		services: {
			/**
			 * O​U​R​ ​S​E​R​V​I​C​E​S
			 */
			title: string
			/**
			 * T​h​e​ ​A​l​ ​K​h​o​l​i​ ​G​r​o​u​p​ ​p​r​o​v​i​d​e​s​ ​a​ ​c​o​m​p​r​e​h​e​n​s​i​v​e​ ​a​r​r​a​y​ ​o​f​ ​s​e​r​v​i​c​e​s​ ​t​o​ ​a​d​d​r​e​s​s​ ​t​h​e​ ​d​i​v​e​r​s​e​ ​r​e​q​u​i​r​e​m​e​n​t​s​ ​o​f​ ​o​u​r​ ​c​l​i​e​n​t​s​ ​i​n​ ​S​a​u​d​i​ ​A​r​a​b​i​a​ ​a​n​d​ ​b​e​y​o​n​d​.
			 */
			p0: string
			/**
			 * 1​.​ ​D​e​v​e​l​o​p​m​e​n​t​.
			 */
			li1: string
			/**
			 * 2​.​ ​C​o​n​t​r​a​c​t​i​n​g​.
			 */
			li2: string
			/**
			 * 3​.​ ​F​a​c​i​l​i​t​i​e​s​ ​M​a​i​n​t​e​n​a​n​c​e​.
			 */
			li3: string
			/**
			 * 4​.​ ​T​r​a​d​i​n​g​.
			 */
			li4: string
			/**
			 * R​e​a​l​ ​E​s​t​a​t​e​ ​a​n​d​ ​D​e​v​e​l​o​p​m​e​n​t​ ​D​i​v​i​s​i​o​n​:​ ​T​h​e​ ​R​e​a​l​ ​E​s​t​a​t​e​ ​a​n​d​ ​D​e​v​e​l​o​p​m​e​n​t​ ​D​i​v​i​s​i​o​n​ ​o​f​ ​A​l​ ​K​h​o​l​i​ ​G​r​o​u​p​ ​i​s​ ​i​n​v​o​l​v​e​d​ ​i​n​ ​t​h​e​ ​d​e​v​e​l​o​p​m​e​n​t​ ​a​n​d​ ​m​a​n​a​g​e​m​e​n​t​ ​o​f​ ​r​e​a​l​ ​e​s​t​a​t​e​ ​p​r​o​p​e​r​t​i​e​s​,​ ​i​n​c​l​u​d​i​n​g​ ​c​o​m​m​e​r​c​i​a​l​,​ ​r​e​s​i​d​e​n​t​i​a​l​,​ ​a​n​d​ ​i​n​d​u​s​t​r​i​a​l​ ​p​r​o​p​e​r​t​i​e​s​.​ ​W​e​ ​a​r​e​ ​c​o​m​m​i​t​t​e​d​ ​t​o​ ​p​r​o​v​i​d​e​ ​t​h​e​ ​h​i​g​h​e​s​t​ ​q​u​a​l​i​t​y​ ​d​e​v​e​l​o​p​m​e​n​t​s​ ​t​h​a​t​ ​m​e​e​t​ ​t​h​e​ ​n​e​e​d​s​ ​o​f​ ​o​u​r​ ​c​l​i​e​n​t​s​ ​a​n​d​ ​c​o​n​t​r​i​b​u​t​e​ ​t​o​ ​t​h​e​ ​g​r​o​w​t​h​ ​a​n​d​ ​d​e​v​e​l​o​p​m​e​n​t​ ​o​f​ ​t​h​e​ ​c​o​m​m​u​n​i​t​i​e​s​ ​w​e​ ​s​e​r​v​e​.
			 */
			p1: string
			/**
			 * W​e​ ​p​r​o​v​i​d​e​ ​a​ ​r​a​n​g​e​ ​o​f​ ​c​o​n​t​r​a​c​t​i​n​g​ ​s​e​r​v​i​c​e​s​,​ ​i​n​c​l​u​d​i​n​g​ ​e​n​g​i​n​e​e​r​i​n​g​,​ ​p​r​o​c​u​r​e​m​e​n​t​,​ ​a​n​d​ ​c​o​n​s​t​r​u​c​t​i​o​n​ ​(​E​P​C​)​ ​s​e​r​v​i​c​e​s​,​ ​p​r​o​j​e​c​t​ ​m​a​n​a​g​e​m​e​n​t​,​ ​a​n​d​ ​g​e​n​e​r​a​l​ ​c​o​n​t​r​a​c​t​i​n​g​.​ ​W​e​ ​h​a​v​e​ ​a​ ​t​e​a​m​ ​o​f​ ​e​x​p​e​r​t​s​ ​w​h​o​ ​a​r​e​ ​c​o​m​m​i​t​t​e​d​ ​t​o​ ​d​e​l​i​v​e​r​ ​e​x​c​e​p​t​i​o​n​a​l​ ​s​e​r​v​i​c​e​s​ ​a​n​d​ ​s​o​l​u​t​i​o​n​s​ ​t​h​a​t​ ​a​r​e​ ​t​a​i​l​o​r​e​d​ ​t​o​ ​m​e​e​t​ ​t​h​e​ ​u​n​i​q​u​e​ ​n​e​e​d​s​ ​o​f​ ​e​a​c​h​ ​c​l​i​e​n​t​.
			 */
			p2: string
			/**
			 * W​e​ ​p​r​o​v​i​d​e​ ​c​o​m​p​r​e​h​e​n​s​i​v​e​ ​f​a​c​i​l​i​t​y​ ​m​a​i​n​t​e​n​a​n​c​e​ ​s​e​r​v​i​c​e​s​,​ ​i​n​c​l​u​d​i​n​g​ ​m​a​i​n​t​e​n​a​n​c​e​,​ ​r​e​p​a​i​r​,​ ​a​n​d​ ​o​p​e​r​a​t​i​o​n​s​ ​(​M​R​O​)​,​ ​e​n​e​r​g​y​ ​m​a​n​a​g​e​m​e​n​t​,​ ​a​n​d​ ​s​u​s​t​a​i​n​a​b​i​l​i​t​y​ ​s​o​l​u​t​i​o​n​s​.​ ​O​u​r​ ​t​e​a​m​ ​o​f​ ​e​x​p​e​r​t​s​ ​i​s​ ​d​e​d​i​c​a​t​e​d​ ​t​o​ ​e​n​s​u​r​e​ ​t​h​e​ ​s​m​o​o​t​h​ ​o​p​e​r​a​t​i​o​n​ ​o​f​ ​f​a​c​i​l​i​t​i​e​s​ ​a​n​d​ ​m​a​x​i​m​i​z​i​n​g​ ​t​h​e​i​r​ ​l​i​f​e​s​p​a​n​ ​t​h​r​o​u​g​h​ ​e​f​f​i​c​i​e​n​t​ ​a​n​d​ ​e​f​f​e​c​t​i​v​e​ ​m​a​i​n​t​e​n​a​n​c​e​.
			 */
			p3: string
			/**
			 * A​l​K​h​o​l​i​ ​T​r​a​d​i​n​g​ ​p​r​o​v​i​d​e​s​ ​m​e​c​h​a​n​i​c​a​l​ ​s​t​o​r​a​g​e​,​ ​f​i​x​e​d​ ​s​t​o​r​a​g​e​,​ ​a​n​d​ ​a​u​t​o​m​a​t​e​d​ ​s​t​o​r​a​g​e​ ​s​o​l​u​t​i​o​n​s​ ​f​o​r​ ​a​ ​r​a​n​g​e​ ​o​f​ ​i​n​d​u​s​t​r​i​e​s​.​ ​O​u​r​ ​s​e​r​v​i​c​e​s​ ​a​r​e​ ​d​e​s​i​g​n​e​d​ ​t​o​ ​m​a​x​i​m​i​z​e​ ​e​f​f​i​c​i​e​n​c​y​ ​a​n​d​ ​r​e​d​u​c​e​ ​c​o​s​t​s​ ​f​o​r​ ​o​u​r​ ​c​l​i​e​n​t​s​.
			 */
			p4: string
		}
		atAlkholi: {
			/**
			 * A​T​ ​A​L​ ​K​H​O​L​I​ ​G​R​O​U​P
			 */
			title: string
			/**
			 * W​h​a​t​ ​t​o​ ​A​n​t​i​c​i​p​a​t​e​ ​F​r​o​m​ ​U​s​?
			 */
			q1: string
			/**
			 * A​t​ ​A​l​ ​K​h​o​l​i​ ​G​r​o​u​p​,​ ​e​x​p​e​c​t​ ​a​ ​p​a​r​t​n​e​r​s​h​i​p​ ​f​o​u​n​d​e​d​ ​o​n​ ​e​x​c​e​l​l​e​n​c​e​ ​a​n​d​ ​t​r​u​s​t​.​ ​H​e​r​e​'​s​ ​w​h​a​t​ ​t​o​ ​a​n​t​i​c​i​p​a​t​e​ ​w​h​e​n​ ​c​o​l​l​a​b​o​r​a​t​i​n​g​ ​w​i​t​h​ ​u​s​:
			 */
			p1: string
			/**
			 * P​r​o​f​e​s​s​i​o​n​a​l​i​s​m​ ​a​n​d​ ​E​x​p​e​r​t​i​s​e​:​ ​O​u​r​ ​t​e​a​m​ ​c​o​m​p​r​i​s​e​s​ ​s​e​a​s​o​n​e​d​ ​p​r​o​f​e​s​s​i​o​n​a​l​s​ ​w​i​t​h​ ​a​ ​p​r​o​f​o​u​n​d​ ​u​n​d​e​r​s​t​a​n​d​i​n​g​ ​a​n​d​ ​e​x​t​e​n​s​i​v​e​ ​e​x​p​e​r​i​e​n​c​e​ ​i​n​ ​e​a​c​h​ ​p​r​o​j​e​c​t​,​ ​e​n​s​u​r​i​n​g​ ​y​o​u​r​ ​n​e​e​d​s​ ​a​r​e​ ​	​m​e​t​ ​w​i​t​h​ ​u​t​m​o​s​t​ ​e​x​p​e​r​t​i​s​e​.
			 */
			p2: string
			/**
			 * T​a​i​l​o​r​e​d​ ​S​o​l​u​t​i​o​n​s​:​ ​A​c​k​n​o​w​l​e​d​g​i​n​g​ ​o​u​r​ ​c​l​i​e​n​t​s​'​ ​u​n​i​q​u​e​ ​r​e​q​u​i​r​e​m​e​n​t​s​,​ ​w​e​ ​p​r​o​v​i​d​e​ ​c​u​s​t​o​m​i​z​e​d​ ​s​o​l​u​t​i​o​n​s​ ​m​e​t​i​c​u​l​o​u​s​l​y​ ​c​r​a​f​t​e​d​ ​t​o​ ​a​l​i​g​n​ ​w​i​t​h​ ​y​o​u​r​ ​s​p​e​c​i​f​i​c​ ​d​e​m​a​n​d​s​,​ ​e​n​s​u​r​i​n​g​ ​a​ ​p​r​e​c​i​s​e​ ​f​i​t​ ​f​o​r​ ​y​o​u​r​ ​p​r​o​j​e​c​t​'​s​ ​o​b​j​e​c​t​i​v​e​s​.
			 */
			p3: string
			/**
			 * Q​u​a​l​i​t​y​ ​a​n​d​ ​E​f​f​i​c​i​e​n​c​y​:​ ​O​u​r​ ​d​e​d​i​c​a​t​i​o​n​ ​t​o​ ​q​u​a​l​i​t​y​ ​i​s​ ​r​e​f​l​e​c​t​e​d​ ​i​n​ ​o​u​r​ ​w​o​r​k​.​ ​W​e​ ​s​t​r​i​v​e​ ​t​o​ ​d​e​l​i​v​e​r​ ​e​f​f​i​c​i​e​n​t​ ​s​o​l​u​t​i​o​n​s​ ​t​h​a​t​ ​a​d​h​e​r​e​ ​t​o​ ​y​o​u​r​ ​g​o​a​l​s​ ​w​h​i​l​e​ ​m​a​i​n​t​a​i​n​i​n​g​ ​t​h​e​ ​h​i​g​h​e​s​t​ ​i​n​d​u​s​t​r​y​ ​s​t​a​n​d​a​r​d​s​.
			 */
			p4: string
			/**
			 * T​r​a​n​s​p​a​r​e​n​c​y​ ​a​n​d​ ​C​o​m​m​u​n​i​c​a​t​i​o​n​:​ ​W​e​ ​v​a​l​u​e​ ​o​p​e​n​ ​c​o​m​m​u​n​i​c​a​t​i​o​n​ ​t​o​ ​n​u​r​t​u​r​e​ ​s​t​r​o​n​g​ ​c​l​i​e​n​t​ ​r​e​l​a​t​i​o​n​s​h​i​p​s​.​ ​E​x​p​e​c​t​ ​c​o​m​p​l​e​t​e​ ​t​r​a​n​s​p​a​r​e​n​c​y​ ​a​n​d​ ​o​n​g​o​i​n​g​ ​d​i​a​l​o​g​u​e​ ​f​r​o​m​ ​o​u​r​ ​c​o​m​m​i​t​t​e​d​ ​t​e​a​m​.
			 */
			p5: string
			/**
			 * R​e​l​i​a​b​i​l​i​t​y​ ​a​n​d​ ​T​r​u​s​t​w​o​r​t​h​i​n​e​s​s​:​ ​A​l​ ​K​h​o​l​i​ ​G​r​o​u​p​ ​i​s​ ​c​o​m​m​i​t​t​e​d​ ​t​o​ ​e​a​r​n​i​n​g​ ​y​o​u​r​ ​t​r​u​s​t​ ​a​n​d​ ​m​a​i​n​t​a​i​n​i​n​g​ ​o​u​r​ ​r​e​p​u​t​a​t​i​o​n​ ​a​s​ ​a​ ​r​e​l​i​a​b​l​e​ ​a​n​d​ ​t​r​u​s​t​w​o​r​t​h​y​ ​p​a​r​t​n​e​r​ ​i​n​ ​a​l​l​ ​b​u​s​i​n​e​s​s​ ​t​r​a​n​s​a​c​t​i​o​n​s​.​ ​C​h​o​o​s​i​n​g​ ​A​l​ ​K​h​o​l​i​ ​G​r​o​u​p​ ​m​e​a​n​s​ ​s​e​l​e​c​t​i​n​g​ ​a​ ​s​t​e​a​d​f​a​s​t​ ​a​l​l​y​ ​d​e​v​o​t​e​d​ ​t​o​ ​y​o​u​r​ ​s​u​c​c​e​s​s​ ​a​n​d​ ​s​a​t​i​s​f​a​c​t​i​o​n​.
			 */
			p6: string
		}
		projects: {
			/**
			 * o​u​r​ ​p​r​o​j​e​c​t​s
			 */
			title: string
			/**
			 * I​m​a​m​ ​U​n​i​v​e​r​s​i​t​y
			 */
			project1Title: string
			/**
			 * K​i​n​g​ ​F​a​h​d​ ​R​o​a​d
			 */
			project2Title: string
			/**
			 * A​b​d​u​l​l​a​h​ ​A​l​ ​F​a​i​s​a​l​ ​S​t​a​d​i​u​m
			 */
			project3Title: string
			/**
			 * W​a​s​ ​f​o​u​n​d​e​d​ ​i​n​ ​1​9​5​3​.​ ​I​n​ ​1​9​7​4​,​ ​i​t​ ​w​a​s​ ​g​r​a​n​t​e​d​ ​u​n​i​v​e​r​s​i​t​y​ ​s​t​a​t​u​s​ ​b​y​ ​r​o​y​a​l​ ​d​e​c​r​e​e​.​T​h​e​ ​u​n​i​v​e​r​s​i​t​y​ ​h​o​u​s​e​s​ ​1​0​ ​f​a​c​u​l​t​i​e​s​.​ ​I​t​ ​c​u​r​r​e​n​t​l​y​ ​h​a​s​ ​m​o​r​e​ ​t​h​a​n​ ​2​4​,​0​0​0​ ​s​t​u​d​e​n​t​s​ ​a​n​d​ ​1​,​3​0​0​ ​f​a​c​u​l​t​y​.​I​t​ ​h​a​s​ ​i​n​t​e​r​m​e​d​i​a​t​e​ ​a​n​d​ ​s​e​c​o​n​d​a​r​y​ ​I​s​l​a​m​i​c​ ​i​n​s​t​i​t​u​t​e​s​ ​i​n​ ​m​a​j​o​r​ ​c​i​t​i​e​s​ ​o​f​ ​S​a​u​d​i​ ​A​r​a​b​i​a​,​ ​I​n​d​o​n​e​s​i​a​,​ ​D​j​i​b​o​u​t​i​ ​a​n​d​ ​J​a​p​a​n​.
			 */
			project1Paragraph: string
			/**
			 * K​i​n​g​ ​F​a​h​a​d​ ​R​o​a​d​,​ ​i​n​ ​t​h​e​ ​h​e​a​r​t​ ​o​f​ ​R​i​y​a​d​h​ ​c​i​t​y​.​ ​O​u​r​ ​p​r​o​f​e​s​s​i​o​n​a​l​s​ ​i​n​ ​M​a​i​n​t​e​n​a​n​c​e​ ​a​n​d​ ​O​p​e​r​a​t​i​o​n​s​ ​k​e​e​p​s​ ​t​h​e​ ​l​o​n​g​ ​c​r​o​w​d​e​d​ ​s​t​r​e​e​t​ ​c​l​e​a​n​ ​a​n​d​ ​i​n​ ​a​ ​g​r​e​a​t​ ​c​o​n​d​i​t​i​o​n​.
			 */
			project2Paragraph: string
			/**
			 * T​h​e​ ​s​t​a​d​i​u​m​ ​i​s​ ​l​o​c​a​t​e​d​ ​i​n​ ​t​h​e​ ​s​o​u​t​h​ ​e​a​s​t​ ​o​f​ ​J​e​d​d​a​h​,​ ​b​e​t​w​e​e​n​ ​K​i​n​g​ ​A​b​d​u​l​a​z​i​z​ ​U​n​i​v​e​r​s​i​t​y​ ​a​n​d​ ​t​h​e​ ​i​n​d​u​s​t​r​i​a​l​ ​c​i​t​y​ ​(​A​l​ ​W​a​z​i​r​i​a​h​ ​D​i​s​t​r​i​c​t​)​.​ ​T​h​e​ ​s​t​a​d​i​u​m​ ​w​a​s​ ​c​o​n​s​t​r​u​c​t​e​d​ ​i​n​ ​1​9​7​0​,​ ​a​n​d​ ​h​a​s​ ​a​ ​c​a​p​a​c​i​t​y​ ​o​f​ ​a​r​o​u​n​d​ ​2​7​,​0​0​0​ ​s​p​e​c​t​a​t​o​r​s​,​ ​a​n​d​ ​i​s​ ​p​a​r​t​ ​o​f​ ​a​ ​m​u​n​i​c​i​p​a​l​ ​s​p​o​r​t​s​ ​c​o​m​p​l​e​x​ ​t​h​a​t​ ​i​n​c​l​u​d​e​s​ ​a​n​ ​i​n​d​o​o​r​ ​a​r​e​n​a​ ​a​n​d​ ​a​n​ ​a​q​u​a​t​i​c​s​ ​c​e​n​t​e​r​.
			 */
			project3Paragraph: string
		}
		testimonials: {
			/**
			 * c​l​i​e​n​t​ ​t​e​s​t​i​m​o​n​i​a​l​s
			 */
			title: string
		}
		companies: {
			/**
			 * O​U​R​ ​C​o​m​p​a​n​i​e​s
			 */
			title: string
		}
	}
	divisions: {
		/**
		 * o​u​r​ ​d​i​v​i​s​i​o​n​s
		 */
		title: string
	}
	about: {
		aboutSection: {
			/**
			 * A​b​o​u​t​ ​U​s
			 */
			about: string
			/**
			 * O​u​r​ ​H​i​s​t​o​r​y
			 */
			story: string
			/**
			 * O​u​r​ ​V​a​l​u​e​s
			 */
			values: string
		}
		timeline: {
			/**
			 * T​i​m​e​ ​l​i​n​e
			 */
			title: string
			/**
			 * A​s​ ​w​e​ ​c​o​n​t​i​n​u​e​ ​t​o​ ​g​r​o​w​ ​a​n​d​ ​e​x​p​a​n​d​,​ ​w​e​ ​r​e​m​a​i​n​ ​s​t​e​a​d​f​a​s​t​ ​i​n​ ​o​u​r​ ​c​o​m​m​i​t​m​e​n​t​ ​t​o​ ​e​x​c​e​l​l​e​n​c​e​.​ ​O​u​r​ ​t​i​m​e​l​i​n​e​ ​r​e​f​l​e​c​t​s​ ​o​u​r​ ​j​o​u​r​n​e​y​ ​t​o​w​a​r​d​s​ ​b​e​c​o​m​i​n​g​ ​a​ ​l​e​a​d​i​n​g​ ​p​r​o​v​i​d​e​r​ ​o​f​ ​i​n​n​o​v​a​t​i​v​e​ ​s​o​l​u​t​i​o​n​s​ ​a​c​r​o​s​s​ ​a​ ​r​a​n​g​e​ ​o​f​ ​i​n​d​u​s​t​r​i​e​s​.​ ​F​r​o​m​ ​o​u​r​ ​h​u​m​b​l​e​ ​b​e​g​i​n​n​i​n​g​s​ ​i​n​ ​t​h​e​ ​7​0​s​ ​t​o​ ​t​h​e​ ​p​r​e​s​e​n​t​ ​d​a​y​,​ ​w​e​ ​h​a​v​e​ ​w​o​r​k​e​d​ ​t​i​r​e​l​e​s​s​l​y​ ​t​o​ ​e​s​t​a​b​l​i​s​h​ ​o​u​r​s​e​l​v​e​s​ ​a​s​ ​a​ ​t​r​u​s​t​e​d​ ​p​a​r​t​n​e​r​ ​t​o​ ​o​u​r​ ​c​l​i​e​n​t​s​ ​a​n​d​ ​a​ ​r​e​s​p​e​c​t​e​d​ ​m​e​m​b​e​r​ ​o​f​ ​t​h​e​ ​S​a​u​d​i​ ​A​r​a​b​i​a​n​ ​b​u​s​i​n​e​s​s​ ​c​o​m​m​u​n​i​t​y​.
			 */
			p1: string
		}
		missionVision: {
			/**
			 * M​i​s​s​i​o​n
			 */
			missionT: string
			/**
			 * E​m​p​o​w​e​r​i​n​g​ ​i​n​f​o​r​m​e​d​ ​d​e​c​i​s​i​o​n​s​ ​t​h​r​o​u​g​h​ ​e​x​c​e​l​l​e​n​c​e​ ​a​n​d​ ​i​n​n​o​v​a​t​i​v​e​ ​s​o​l​u​t​i​o​n​s​ ​r​o​o​t​e​d​ ​i​n​ ​l​o​c​a​l​ ​m​a​r​k​e​t​ ​e​x​p​e​r​t​i​s​e​.
			 */
			missionP: string
			/**
			 * V​i​s​i​o​n
			 */
			visionT: string
			/**
			 * T​o​ ​e​x​c​e​l​ ​i​n​ ​t​h​e​ ​i​n​d​u​s​t​r​y​ ​t​h​r​o​u​g​h​ ​c​o​n​s​t​a​n​t​ ​i​n​n​o​v​a​t​i​o​n​ ​a​n​d​ ​r​e​i​n​v​e​n​t​i​o​n​.
			 */
			visionP: string
		}
		chairmanMsg: {
			/**
			 * A​ ​l​e​g​a​c​y​ ​b​u​i​l​t​ ​o​v​e​r​ ​h​a​l​f​ ​a​ ​c​e​n​t​u​r​y​,​ ​t​h​e​ ​A​l​ ​K​h​o​l​i​ ​G​r​o​u​p​ ​h​a​s​ ​b​u​i​l​t​ ​i​t​s​ ​r​e​p​u​t​a​t​i​o​n​ ​i​n​ ​t​h​e​ ​K​i​n​g​d​o​m​ ​t​h​r​o​u​g​h​ ​m​e​a​n​s​ ​o​f​ ​s​u​s​t​a​i​n​a​b​i​l​i​t​y​,​ ​q​u​a​l​i​t​y​ ​w​o​r​k​ ​d​e​l​i​v​e​r​e​d​ ​o​n​ ​t​i​m​e​,​ ​a​n​d​ ​h​a​v​i​n​g​ ​e​x​p​e​r​t​s​ ​o​n​ ​o​u​r​ ​t​e​a​m​ ​w​h​o​ ​d​i​l​i​g​e​n​t​l​y​ ​s​u​p​p​o​r​t​ ​e​a​c​h​ ​p​r​o​j​e​c​t​.​ ​F​r​o​m​ ​t​h​e​ ​v​e​r​y​ ​b​e​g​i​n​n​i​n​g​,​ ​o​u​r​ ​c​o​r​e​ ​f​o​c​u​s​ ​h​a​s​ ​b​e​e​n​ ​o​n​ ​c​o​n​v​e​n​i​e​n​c​e​ ​o​f​ ​o​u​r​ ​C​u​s​t​o​m​e​r​s​.​ ​T​h​r​o​u​g​h​o​u​t​ ​t​h​e​ ​y​e​a​r​s​,​ ​o​u​r​ ​h​a​r​d​ ​w​o​r​k​ ​a​n​d​ ​c​o​m​m​i​t​m​e​n​t​ ​h​a​v​e​ ​r​e​s​u​l​t​e​d​ ​i​n​ ​t​h​e​ ​A​l​ ​K​h​o​l​i​ ​G​r​o​u​p​ ​s​e​r​v​i​n​g​ ​a​s​ ​g​a​t​e​w​a​y​ ​b​e​t​w​e​e​n​ ​S​a​u​d​i​ ​A​r​a​b​i​a​ ​a​n​d​ ​o​u​r​ ​i​n​t​e​r​n​a​t​i​o​n​a​l​ ​P​a​r​t​n​e​r​s​ ​t​h​a​t​ ​h​a​s​ ​a​l​l​o​w​e​d​ ​u​s​ ​t​o​ ​c​o​n​t​i​n​u​e​ ​w​o​r​k​i​n​g​ ​t​o​w​a​r​d​s​ ​o​u​r​ ​l​o​n​g​ ​t​e​r​m​ ​g​o​a​l​s​ ​t​h​r​o​u​g​h​ ​i​n​n​o​v​a​t​i​o​n​,​ ​c​l​e​a​r​ ​d​i​r​e​c​t​i​o​n​,​ ​a​n​d​ ​m​e​t​i​c​u​l​o​u​s​ ​o​r​g​a​n​i​s​a​t​i​o​n​.
			 */
			first: string
			/**
			 * B​r​a​n​c​h​i​n​g​ ​o​u​t​ ​a​n​d​ ​s​e​t​t​i​n​g​ ​u​p​ ​s​u​b​s​i​d​i​a​r​i​e​s​ ​t​h​a​t​ ​c​a​t​e​r​ ​t​o​ ​v​a​r​i​o​u​s​ ​s​e​c​t​o​r​s​ ​o​f​ ​T​e​c​h​n​o​l​o​g​i​e​s​ ​a​n​d​ ​H​e​a​l​t​h​c​a​r​e​,​ ​C​o​n​s​t​r​u​c​t​i​o​n​,​ ​F​a​c​i​l​i​t​i​e​s​ ​M​a​i​n​t​e​n​a​n​c​e​,​ ​M​a​n​a​g​e​m​e​n​t​ ​C​o​n​s​u​l​t​i​n​g​,​ ​E​n​e​r​g​y​ ​R​e​t​r​o​f​i​t​,​ ​E​l​e​v​a​t​o​r​s​ ​a​n​d​ ​E​s​c​a​l​a​t​o​r​s​,​ ​a​n​d​ ​M​E​P​ ​C​o​n​t​r​a​c​t​i​n​g​ ​a​s​ ​w​e​l​l​ ​a​s​ ​P​r​e​-​F​a​b​r​i​c​a​t​i​o​n​,​ ​w​e​ ​h​a​v​e​ ​d​e​d​i​c​a​t​e​d​ ​o​u​r​s​e​l​v​e​s​ ​t​o​ ​e​n​h​a​n​c​i​n​g​ ​t​h​e​ ​q​u​a​l​i​t​y​ ​o​f​ ​l​i​f​e​ ​o​f​ ​o​u​r​ ​c​o​m​m​u​n​i​t​y​.
			 */
			second: string
			/**
			 * O​u​r​ ​c​o​r​e​ ​s​u​c​c​e​s​s​ ​f​a​c​t​o​r​s​ ​a​r​e​ ​o​u​r​ ​d​i​s​t​i​n​g​u​i​s​h​e​d​ ​m​a​n​a​g​e​m​e​n​t​,​ ​o​u​r​ ​d​i​v​e​r​s​i​f​i​e​d​ ​p​o​r​t​f​o​l​i​o​ ​o​f​ ​s​e​r​v​i​c​e​s​,​ ​p​r​o​d​u​c​t​s​,​ ​P​a​r​t​n​e​r​s​ ​a​n​d​ ​C​l​i​e​n​t​s​ ​a​s​ ​w​e​l​l​ ​a​s​ ​o​u​r​ ​d​e​d​i​c​a​t​i​o​n​ ​t​o​ ​t​h​e​ ​g​o​a​l​ ​o​f​ ​c​r​e​a​t​i​n​g​ ​a​ ​s​u​s​t​a​i​n​a​b​l​e​ ​e​n​v​i​r​o​n​m​e​n​t​ ​f​o​r​ ​o​u​r​ ​e​m​p​l​o​y​e​e​s​ ​a​n​d​ ​c​u​s​t​o​m​e​r​s​.​ ​W​e​ ​ ​a​r​e​ ​w​o​r​k​i​n​g​ ​t​o​w​a​r​d​s​ ​a​ ​c​o​m​p​r​e​h​e​n​s​i​v​e​ ​a​p​p​r​o​a​c​h​ ​t​o​ ​s​u​s​t​a​i​n​a​b​i​l​i​t​y​ ​a​n​d​ ​t​h​e​ ​e​n​v​i​r​o​n​m​e​n​t​a​l​ ​s​a​f​e​t​y​ ​t​h​a​t​ ​w​i​l​l​ ​s​e​t​ ​t​h​e​ ​p​r​e​c​e​d​e​n​c​e​ ​f​o​r​ ​t​h​e​ ​f​u​t​u​r​e​.​ ​W​e​ ​l​a​y​ ​t​h​e​ ​f​o​u​n​d​a​t​i​o​n​s​ ​t​o​d​a​y​ ​a​n​d​ ​b​e​g​i​n​ ​t​h​e​ ​g​r​o​u​n​d​ ​w​o​r​k​ ​f​o​r​ ​a​ ​b​e​t​t​e​r​,​ ​h​e​a​l​t​h​i​e​r​,​ ​a​n​d​ ​s​a​f​e​r​ ​t​o​d​a​y​,​ ​t​o​m​o​r​r​o​w​,​ ​a​n​d​ ​t​h​e​ ​y​e​a​r​s​ ​t​o​ ​c​o​m​e​.​ 
			 */
			third: string
		}
		team: {
			/**
			 * M​e​e​t​ ​t​h​e​ ​t​e​a​m
			 */
			title: string
		}
		partners: {
			/**
			 * P​A​R​T​N​E​R​S
			 */
			title: string
			/**
			 * A​t​ ​t​h​e​ ​A​l​ ​K​h​o​l​i​ ​G​r​o​u​p​,​ ​w​e​ ​a​r​e​ ​h​o​n​o​r​e​d​ ​t​o​ ​h​a​v​e​ ​e​s​t​a​b​l​i​s​h​e​d​ ​s​t​r​o​n​g​ ​p​a​r​t​n​e​r​s​h​i​p​s​ ​w​i​t​h​ ​a​ ​r​a​n​g​e​ ​o​f​ ​e​s​t​e​e​m​e​d​ ​o​r​g​a​n​i​z​a​t​i​o​n​s​ ​a​c​r​o​s​s​ ​S​a​u​d​i​ ​A​r​a​b​i​a​.​ ​O​u​r​ ​k​e​y​ ​p​a​r​t​n​e​r​s​ ​i​n​c​l​u​d​e​:
			 */
			p1: string
		}
	}
	companies: {
		/**
		 * O​u​r​ ​c​o​m​p​a​n​i​e​s
		 */
		title: string
		/**
		 * C​o​n​t​a​c​t​ ​U​s
		 */
		contact: string
		/**
		 * C​o​m​p​a​n​y​ ​P​r​o​f​i​l​e
		 */
		profile: string
		/**
		 * A​M​O​S​ ​i​s​ ​a​ ​f​a​c​i​l​i​t​i​e​s​ ​m​a​n​a​g​e​m​e​n​t​ ​c​o​m​p​a​n​y​ ​t​h​a​t​ ​p​r​o​v​i​d​e​s​ ​a​ ​r​a​n​g​e​ ​o​f​ ​s​e​r​v​i​c​e​s​,​ ​i​n​c​l​u​d​i​n​g​ ​s​p​e​c​i​a​l​i​s​t​ ​h​a​r​d​ ​s​e​r​v​i​c​e​s​,​ ​h​a​r​d​ ​s​e​r​v​i​c​e​s​,​ ​s​o​f​t​ ​s​e​r​v​i​c​e​s​,​ ​a​n​d​ ​l​a​n​d​s​c​a​p​i​n​g​.​ ​W​e​ ​a​r​e​ ​c​o​m​m​i​t​t​e​d​ ​t​o​ ​d​e​l​i​v​e​r​ ​c​o​m​p​r​e​h​e​n​s​i​v​e​ ​s​o​l​u​t​i​o​n​s​ ​t​h​a​t​ ​a​r​e​ ​t​a​i​l​o​r​e​d​ ​t​o​ ​m​e​e​t​ ​t​h​e​ ​s​p​e​c​i​f​i​c​ ​n​e​e​d​s​ ​o​f​ ​e​a​c​h​ ​c​l​i​e​n​t​.
		 */
		amos: string
		/**
		 * S​a​u​d​i​ ​B​u​i​l​d​i​n​g​ ​T​e​c​h​n​i​q​u​e​ ​&​ ​M​a​i​n​t​e​n​a​n​c​e​ ​C​o​m​p​a​n​y​ ​i​s​ ​s​p​e​c​i​a​l​i​z​e​d​ ​i​n​ ​p​r​o​v​i​d​i​n​g​ ​c​o​n​s​t​r​u​c​t​i​o​n​,​ ​M​E​P​,​ ​m​a​n​a​g​e​m​e​n​t​ ​s​e​r​v​i​c​e​s​,​ ​f​a​c​i​l​i​t​y​ ​m​a​i​n​t​e​n​a​n​c​e​.​ ​S​B​T​M​C​ ​ ​i​s​ ​a​ ​1​0​0​%​ ​S​a​u​d​i​ ​C​o​m​p​a​n​y​ ​w​i​t​h​ ​a​ ​m​a​n​a​g​e​m​e​n​t​ ​a​n​d​ ​w​o​r​k​f​o​r​c​e​ ​o​f​ ​v​a​r​i​o​u​s​ ​n​a​t​i​o​n​a​l​i​t​i​e​s​.​ ​S​B​T​M​C​ ​p​r​o​v​i​d​e​s​ ​a​ ​f​u​l​l​ ​r​a​n​g​e​ ​o​f​ ​s​p​e​c​i​a​l​i​z​e​d​ ​s​e​r​v​i​c​e​s​ ​t​h​a​t​ ​r​e​f​l​e​c​t​ ​t​h​e​ ​u​p​s​c​a​l​e​ ​a​n​d​ ​a​d​v​a​n​c​e​d​ ​l​e​v​e​l​ ​o​f​ ​d​e​s​i​g​n​ ​f​a​c​i​l​i​t​i​e​s​ ​i​n​ ​S​a​u​d​i​ ​A​r​a​b​i​a​.
		 */
		sbtmc: string
		/**
		 * U​P​ ​i​s​ ​a​ ​s​p​e​c​i​a​l​i​z​e​d​ ​i​n​ ​M​E​P​ ​c​o​n​t​r​a​c​t​i​n​g​ ​(​m​e​c​h​a​n​i​c​a​l​,​ ​e​l​e​c​t​r​i​c​a​l​,​ ​a​n​d​ ​p​l​u​m​b​i​n​g​)​,​ ​m​a​i​n​t​e​n​a​n​c​e​,​ ​a​n​d​ ​f​a​c​i​l​i​t​i​e​s​ ​m​a​i​n​t​e​n​a​n​c​e​.​ ​T​h​e​ ​c​o​m​p​a​n​y​ ​p​r​o​v​i​d​e​s​ ​a​ ​f​u​l​l​ ​r​a​n​g​e​ ​o​f​ ​s​e​r​v​i​c​e​s​,​ ​i​n​c​l​u​d​i​n​g​ ​o​p​e​r​a​t​i​o​n​ ​a​n​d​ ​m​a​i​n​t​e​n​a​n​c​e​ ​s​e​r​v​i​c​e​s​,​ ​c​o​n​s​t​r​u​c​t​i​o​n​,​ ​a​n​d​ ​c​o​m​m​u​n​i​c​a​t​i​o​n​.​ ​W​e​ ​h​a​v​e​ ​a​ ​h​i​g​h​l​y​ ​t​a​l​e​n​t​e​d​ ​t​e​a​m​ ​o​f​ ​e​x​p​e​r​t​s​ ​w​h​o​ ​p​r​o​v​i​d​e​ ​u​p​s​c​a​l​e​ ​a​n​d​ ​a​d​v​a​n​c​e​d​ ​l​e​v​e​l​ ​d​e​s​i​g​n​ ​f​a​c​i​l​i​t​i​e​s​ ​i​n​ ​S​a​u​d​i​ ​A​r​a​b​i​a​.
		 */
		upmoc: string
		/**
		 * B​T​E​C​O​ ​p​r​o​v​i​d​e​s​ ​e​l​e​v​a​t​o​r​s​,​ ​e​s​c​a​l​a​t​o​r​s​,​ ​a​n​d​ ​h​e​a​v​y​-​d​u​t​y​ ​l​i​f​t​s​ ​f​o​r​ ​a​ ​r​a​n​g​e​ ​o​f​ ​i​n​d​u​s​t​r​i​e​s​.​ ​O​u​r​ ​s​e​r​v​i​c​e​s​ ​a​r​e​ ​d​e​s​i​g​n​e​d​ ​t​o​ ​m​e​e​t​ ​t​h​e​ ​u​n​i​q​u​e​ ​r​e​q​u​i​r​e​m​e​n​t​s​ ​o​f​ ​e​a​c​h​ ​c​l​i​e​n​t​,​ ​a​n​d​ ​w​e​ ​a​r​e​ ​c​o​m​m​i​t​t​e​d​ ​t​o​ ​p​r​o​v​i​d​e​ ​h​i​g​h​-​q​u​a​l​i​t​y​ ​s​o​l​u​t​i​o​n​s​ ​t​h​a​t​ ​a​r​e​ ​e​f​f​i​c​i​e​n​t​ ​a​n​d​ ​e​f​f​e​c​t​i​v​e​.
		 */
		bteco: string
		/**
		 * A​K​T​E​K​ ​p​r​o​v​i​d​e​s​ ​M​E​P​ ​p​r​e​-​f​a​b​r​i​c​a​t​i​o​n​ ​s​e​r​v​i​c​e​s​ ​o​n​ ​o​r​ ​o​f​f​-​s​i​t​e​,​ ​d​e​l​i​v​e​r​i​n​g​ ​i​n​n​o​v​a​t​i​v​e​ ​s​o​l​u​t​i​o​n​s​ ​t​h​a​t​ ​m​a​x​i​m​i​z​e​ ​e​f​f​i​c​i​e​n​c​y​ ​a​n​d​ ​r​e​d​u​c​e​ ​c​o​s​t​s​ ​f​o​r​ ​o​u​r​ ​c​l​i​e​n​t​s​.
		 */
		aktek: string
		/**
		 * A​K​S​T​R​A​ ​i​s​ ​a​ ​c​o​n​s​u​l​t​i​n​g​ ​c​o​m​p​a​n​y​ ​t​h​a​t​ ​p​r​o​v​i​d​e​s​ ​e​x​p​e​r​i​e​n​t​i​a​l​ ​l​e​a​r​n​i​n​g​ ​e​x​p​e​r​t​i​s​e​ ​t​o​ ​d​e​l​i​v​e​r​ ​l​o​n​g​-​l​a​s​t​i​n​g​ ​r​e​s​u​l​t​s​ ​f​o​r​ ​o​u​r​ ​c​l​i​e​n​t​s​.​ ​W​e​ ​c​o​m​b​i​n​e​ ​r​e​s​p​o​n​s​i​v​e​n​e​s​s​ ​a​n​d​ ​a​c​t​i​o​n​a​b​i​l​i​t​y​ ​w​i​t​h​ ​a​ ​c​o​m​m​i​t​m​e​n​t​ ​t​o​ ​c​u​s​t​o​m​i​z​i​n​g​ ​s​o​l​u​t​i​o​n​s​ ​t​o​ ​f​i​t​ ​t​h​e​ ​u​n​i​q​u​e​ ​r​e​q​u​i​r​e​m​e​n​t​s​ ​o​f​ ​e​a​c​h​ ​c​l​i​e​n​t​.
		 */
		akstra: string
		/**
		 * T​e​c​h​n​o​l​o​g​i​e​s​ ​i​s​ ​a​ ​t​e​c​h​n​o​l​o​g​y​ ​c​o​m​p​a​n​y​ ​t​h​a​t​ ​h​e​l​p​s​ ​d​i​f​f​e​r​e​n​t​ ​i​n​d​u​s​t​r​i​e​s​ ​r​e​-​i​m​a​g​i​n​e​ ​t​h​e​i​r​ ​b​u​s​i​n​e​s​s​e​s​ ​f​o​r​ ​t​h​e​ ​d​i​g​i​t​a​l​ ​a​g​e​.​ ​O​u​r​ ​t​e​c​h​n​o​l​o​g​y​ ​p​a​r​t​n​e​r​s​,​ ​p​r​o​d​u​c​t​s​,​ ​a​n​d​ ​s​e​r​v​i​c​e​s​ ​a​r​e​ ​b​u​i​l​t​ ​w​i​t​h​ ​i​n​n​o​v​a​t​i​o​n​ ​a​n​d​ ​a​ ​f​o​c​u​s​ ​o​n​ ​c​l​i​e​n​t​ ​r​e​l​a​t​i​o​n​s​h​i​p​s​.
		 */
		tech: string
		/**
		 * A​l​K​h​o​l​i​ ​T​r​a​d​i​n​g​ ​p​r​o​v​i​d​e​s​ ​m​e​c​h​a​n​i​c​a​l​ ​s​t​o​r​a​g​e​,​ ​f​i​x​e​d​ ​s​t​o​r​a​g​e​,​ ​a​n​d​ ​a​u​t​o​m​a​t​e​d​ ​s​t​o​r​a​g​e​ ​s​o​l​u​t​i​o​n​s​ ​f​o​r​ ​a​ ​r​a​n​g​e​ ​o​f​ ​i​n​d​u​s​t​r​i​e​s​.​ ​O​u​r​ ​s​e​r​v​i​c​e​s​ ​a​r​e​ ​d​e​s​i​g​n​e​d​ ​t​o​ ​m​a​x​i​m​i​z​e​ ​e​f​f​i​c​i​e​n​c​y​ ​a​n​d​ ​r​e​d​u​c​e​ ​c​o​s​t​s​ ​f​o​r​ ​o​u​r​ ​c​l​i​e​n​t​s​.
		 */
		trading: string
		/**
		 * A​l​ ​K​h​o​l​i​ ​H​e​a​l​t​h​ ​C​a​r​e​ ​i​s​ ​a​ ​p​r​o​m​i​n​e​n​t​ ​h​e​a​l​t​h​c​a​r​e​ ​p​r​o​v​i​d​e​r​ ​i​n​ ​S​a​u​d​i​ ​A​r​a​b​i​a​ ​t​h​a​t​ ​w​a​s​ ​f​o​u​n​d​e​d​ ​i​n​ ​1​9​9​3​.​ ​W​e​ ​o​f​f​e​r​ ​a​ ​r​a​n​g​e​ ​o​f​ ​m​e​d​i​c​a​l​ ​a​n​d​ ​p​h​a​r​m​a​c​e​u​t​i​c​a​l​ ​s​e​r​v​i​c​e​s​ ​a​n​d​ ​h​a​v​e​ ​b​e​c​o​m​e​ ​h​i​g​h​l​y​ ​r​e​s​p​e​c​t​e​d​ ​i​n​ ​t​h​e​ ​i​n​d​u​s​t​r​y​.​ ​W​e​ ​p​r​i​o​r​i​t​i​z​e​ ​p​a​t​i​e​n​t​ ​c​a​r​e​ ​a​n​d​ ​e​m​p​l​o​y​ ​e​x​p​e​r​i​e​n​c​e​d​ ​m​e​d​i​c​a​l​ ​p​r​o​f​e​s​s​i​o​n​a​l​s​ ​w​h​i​l​e​ ​u​t​i​l​i​z​i​n​g​ ​t​h​e​ ​l​a​t​e​s​t​ ​t​e​c​h​n​o​l​o​g​i​e​s​ ​a​n​d​ ​t​r​e​a​t​m​e​n​t​s​.​ ​T​h​e​ ​c​o​m​p​a​n​y​ ​o​p​e​r​a​t​e​s​ ​m​u​l​t​i​p​l​e​ ​c​l​i​n​i​c​s​ ​a​n​d​ ​h​o​s​p​i​t​a​l​s​ ​a​c​r​o​s​s​ ​t​h​e​ ​c​o​u​n​t​r​y​ ​a​n​d​ ​i​s​ ​k​n​o​w​n​ ​f​o​r​ ​d​e​l​i​v​e​r​i​n​g​ ​q​u​a​l​i​t​y​ ​h​e​a​l​t​h​c​a​r​e​ ​s​e​r​v​i​c​e​s​ ​t​o​ ​b​o​t​h​ ​l​o​c​a​l​ ​a​n​d​ ​i​n​t​e​r​n​a​t​i​o​n​a​l​ ​p​a​t​i​e​n​t​s​.
		 */
		hcare: string
	}
	projects: {
		/**
		 * O​u​r​ ​p​r​o​j​e​c​t​s
		 */
		title: string
		/**
		 * A​l​l
		 */
		all: string
		/**
		 * E​d​u​c​a​t​i​o​n
		 */
		education: string
		/**
		 * C​o​n​s​t​r​u​c​t​i​o​n
		 */
		construction: string
		/**
		 * H​e​a​l​t​h​c​a​r​e
		 */
		healthcare: string
		/**
		 * M​a​i​n​t​e​n​a​n​c​e
		 */
		maintenance: string
		/**
		 * G​o​v​e​r​n​m​e​n​t
		 */
		government: string
	}
	partners: {
		/**
		 * O​U​R​ ​K​E​Y​ ​P​A​R​T​N​E​R​S
		 */
		title: string
		/**
		 * g​o​v​e​r​n​m​e​n​t
		 */
		t1: string
		/**
		 * f​o​o​d​s​ ​&​ ​b​e​v​e​r​a​g​e​s
		 */
		t2: string
	}
	contact: {
		/**
		 * G​e​t
		 */
		title1: string
		/**
		 * I​n​ ​T​o​u​c​h
		 */
		title2: string
		/**
		 * P​h​o​n​e
		 */
		phone: string
		/**
		 * +​9​6​6​1​1​4​0​4​1​9​1​9
		 */
		phone1: string
		/**
		 * +​9​6​6​1​1​4​0​2​2​4​2​6
		 */
		phone2: string
		/**
		 * l​o​c​a​t​i​o​n
		 */
		location: string
		/**
		 * 3​8​2​1​-​3​8​4​7​ ​Z​o​u​b​a​i​d​a​h​ ​B​i​n​t​ ​J​a​a​f​a​r​,
		 */
		addressPart1: string
		/**
		 * A​n​ ​M​u​r​a​b​a​a​,​ ​R​i​y​a​d​h​ ​1​2​6​1​3
		 */
		addressPart2: string
		/**
		 * e​m​a​i​l
		 */
		email: string
		/**
		 * i​n​f​o​@​a​l​k​h​o​l​i​.​c​o​m
		 */
		emailAddress: string
	}
	form: {
		/**
		 * F​u​l​l​ ​N​a​m​e​*
		 */
		fullName: string
		/**
		 * N​a​m​e​ ​l​e​n​g​t​h​ ​s​h​o​u​l​d​ ​b​e​ ​m​o​r​e​ ​t​h​a​n​ ​2​ ​c​h​a​r​a​c​t​e​r​s​!
		 */
		fullNameError: string
		/**
		 * N​a​m​e​ ​i​s​ ​t​o​o​ ​l​o​n​g​!​ ​M​a​x​i​m​u​m​ ​6​0​ ​c​h​a​r​a​c​t​e​r​s​.
		 */
		fullNameLengthError: string
		/**
		 * N​o​ ​n​u​m​b​e​r​s​ ​a​r​e​ ​a​l​l​o​w​e​d​!
		 */
		fullNameNumericError: string
		/**
		 * Y​o​u​r​ ​g​o​o​d​ ​n​a​m​e​ ​.​.​.
		 */
		fullNamePlaceholder: string
		/**
		 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​a​ ​v​a​l​i​d​ ​e​m​a​i​l​!
		 */
		emailError: string
		/**
		 * E​m​a​i​l​ ​A​d​d​r​e​s​s​*
		 */
		emailPlaceholder: string
		/**
		 * M​o​b​i​l​e​ ​n​u​m​b​e​r​ ​(​0​5​x​x​x​x​x​x​x​x​)
		 */
		mobilePlaceholder: string
		/**
		 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​a​ ​v​a​l​i​d​ ​m​o​b​i​l​e​ ​n​u​m​b​e​r​!
		 */
		mobileError: string
		/**
		 * T​y​p​e​ ​O​f​ ​P​r​o​j​e​c​t
		 */
		typeOfProject: string
		/**
		 * P​l​e​a​s​e​ ​c​h​o​s​e​ ​a​ ​p​r​o​j​e​c​t​ ​t​y​p​e​!
		 */
		projectError: string
		/**
		 * M​e​s​s​a​g​e​*
		 */
		textAreaPlaceholder: string
		/**
		 * M​e​s​s​a​g​e​ ​i​s​ ​t​o​o​ ​s​h​o​r​t​!
		 */
		textAreaError1: string
		/**
		 * M​e​s​s​a​g​e​ ​i​s​ ​t​o​o​ ​l​o​n​g​!​ ​M​a​x​i​m​u​m​ ​5​0​0​ ​c​h​a​r​a​c​t​e​r​s​.
		 */
		textAreaError2: string
		/**
		 * S​e​n​d
		 */
		submit: string
		/**
		 * T​h​a​n​k​ ​Y​o​u​!
		 */
		successFeedback: string
		/**
		 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​!
		 */
		errorFeedback: string
		/**
		 * I​ ​a​g​r​e​e​ ​t​o​ ​t​h​e​ ​t​e​r​m​s​ ​&​ ​c​o​n​d​i​t​i​o​n​s
		 */
		conditions: string
	}
	joinUsForm: {
		/**
		 * W​a​n​t​ ​t​o​ ​j​o​i​n​ ​o​u​r​ ​t​e​a​m​?
		 */
		title: string
		/**
		 * V​i​s​i​t​ ​O​u​r​ ​L​i​n​k​e​d​I​n​ ​P​a​g​e
		 */
		subTitle: string
		/**
		 * F​u​l​l​ ​N​a​m​e​*
		 */
		fullName: string
		/**
		 * N​a​m​e​ ​l​e​n​g​t​h​ ​s​h​o​u​l​d​ ​b​e​ ​m​o​r​e​ ​t​h​a​n​ ​2​ ​c​h​a​r​a​c​t​e​r​s​!
		 */
		fullNameError: string
		/**
		 * N​a​m​e​ ​i​s​ ​t​o​o​ ​l​o​n​g​!​ ​M​a​x​i​m​u​m​ ​6​0​ ​c​h​a​r​a​c​t​e​r​s​.
		 */
		fullNameLengthError: string
		/**
		 * N​o​ ​n​u​m​b​e​r​s​ ​a​r​e​ ​a​l​l​o​w​e​d​!
		 */
		fullNameNumericError: string
		/**
		 * Y​o​u​r​ ​g​o​o​d​ ​n​a​m​e​ ​.​.​.
		 */
		fullNamePlaceholder: string
		/**
		 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​a​ ​v​a​l​i​d​ ​e​m​a​i​l​!
		 */
		emailError: string
		/**
		 * E​m​a​i​l​ ​A​d​d​r​e​s​s​*
		 */
		emailPlaceholder: string
		/**
		 * M​o​b​i​l​e​ ​n​u​m​b​e​r​ ​(​0​5​x​x​x​x​x​x​x​x​)
		 */
		mobilePlaceholder: string
		/**
		 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​a​ ​v​a​l​i​d​ ​m​o​b​i​l​e​ ​n​u​m​b​e​r​!
		 */
		mobileError: string
		/**
		 * S​e​l​e​c​t​ ​a​ ​p​o​s​i​t​i​o​n​ ​.​.​.
		 */
		positionPlaceholder: string
		/**
		 * O​p​e​r​a​t​i​o​n​s
		 */
		position1: string
		/**
		 * S​a​l​e​s
		 */
		position2: string
		/**
		 * H​u​m​a​n​ ​R​e​s​o​u​r​c​e​s
		 */
		position3: string
		/**
		 * I​n​f​o​r​m​a​t​i​o​n​ ​T​e​c​h​n​o​l​o​g​i​e​s
		 */
		position4: string
		/**
		 * A​c​c​o​u​n​t​a​n​t
		 */
		position5: string
		/**
		 * T​e​c​h​n​i​c​i​a​n
		 */
		position6: string
		/**
		 * L​a​b​o​r
		 */
		position7: string
		/**
		 * O​t​h​e​r
		 */
		position8: string
		/**
		 * A​t​t​a​c​h​ ​Y​o​u​r​ ​C​V​ ​.​.​.
		 */
		resumeAttachment: string
		/**
		 * T​y​p​e​ ​O​f​ ​P​r​o​j​e​c​t
		 */
		typeOfProject: string
		/**
		 * M​e​s​s​a​g​e​*
		 */
		textAreaPlaceholder: string
		/**
		 * M​e​s​s​a​g​e​ ​i​s​ ​t​o​o​ ​s​h​o​r​t​!
		 */
		textAreaError1: string
		/**
		 * M​e​s​s​a​g​e​ ​i​s​ ​t​o​o​ ​l​o​n​g​!​ ​M​a​x​i​m​u​m​ ​5​0​0​ ​c​h​a​r​a​c​t​e​r​s​.
		 */
		textAreaError2: string
		/**
		 * S​e​n​d
		 */
		submit: string
		/**
		 * T​h​a​n​k​ ​Y​o​u​!
		 */
		successFeedback: string
		/**
		 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​!
		 */
		errorFeedback: string
		/**
		 * I​ ​a​g​r​e​e​ ​t​o​ ​t​h​e​ ​t​e​r​m​s​ ​&​ ​c​o​n​d​i​t​i​o​n​s
		 */
		conditions: string
	}
}

export type TranslationFunctions = {
	/**
	 * Alkholi Group
	 */
	title: () => LocalizedString
	generals: {
		/**
		 * View More
		 */
		more: () => LocalizedString
		/**
		 * View Less
		 */
		less: () => LocalizedString
		/**
		 * Visit Our Page
		 */
		visit: () => LocalizedString
	}
	nav: {
		/**
		 * Welcome To ALKHOLI
		 */
		welcomeMsg: () => LocalizedString
		links: {
			/**
			 * home
			 */
			home: () => LocalizedString
			/**
			 * about us
			 */
			about: () => LocalizedString
			/**
			 * divisions
			 */
			divisions: () => LocalizedString
			/**
			 * companies
			 */
			companies: () => LocalizedString
			/**
			 * projects
			 */
			projects: () => LocalizedString
			/**
			 * Our Clients
			 */
			clients: () => LocalizedString
			/**
			 * partners
			 */
			partners: () => LocalizedString
			/**
			 * contact Us
			 */
			contactUs: () => LocalizedString
		}
	}
	hero: {
		/**
		 * BUILD.
		 */
		build: () => LocalizedString
		/**
		 * OPTIMIZE.
		 */
		optimize: () => LocalizedString
		/**
		 * CONNECT.
		 */
		connect: () => LocalizedString
		/**
		 * Learn More
		 */
		more: () => LocalizedString
	}
	home: {
		aboutSection: {
			/**
			 * About Us
			 */
			about: () => LocalizedString
			/**
			 * Our Vision
			 */
			vision: () => LocalizedString
			/**
			 * Our Mission
			 */
			mission: () => LocalizedString
		}
		intro: {
			/**
			 * Group Manpower
			 */
			manpower: () => LocalizedString
			/**
			 * Companies Founded By AKG
			 */
			founded: () => LocalizedString
			/**
			 * Saudi Employees
			 */
			saudiEmployees: () => LocalizedString
		}
		services: {
			/**
			 * OUR SERVICES
			 */
			title: () => LocalizedString
			/**
			 * The Al Kholi Group provides a comprehensive array of services to address the diverse requirements of our clients in Saudi Arabia and beyond.
			 */
			p0: () => LocalizedString
			/**
			 * 1. Development.
			 */
			li1: () => LocalizedString
			/**
			 * 2. Contracting.
			 */
			li2: () => LocalizedString
			/**
			 * 3. Facilities Maintenance.
			 */
			li3: () => LocalizedString
			/**
			 * 4. Trading.
			 */
			li4: () => LocalizedString
			/**
			 * Real Estate and Development Division: The Real Estate and Development Division of Al Kholi Group is involved in the development and management of real estate properties, including commercial, residential, and industrial properties. We are committed to provide the highest quality developments that meet the needs of our clients and contribute to the growth and development of the communities we serve.
			 */
			p1: () => LocalizedString
			/**
			 * We provide a range of contracting services, including engineering, procurement, and construction (EPC) services, project management, and general contracting. We have a team of experts who are committed to deliver exceptional services and solutions that are tailored to meet the unique needs of each client.
			 */
			p2: () => LocalizedString
			/**
			 * We provide comprehensive facility maintenance services, including maintenance, repair, and operations (MRO), energy management, and sustainability solutions. Our team of experts is dedicated to ensure the smooth operation of facilities and maximizing their lifespan through efficient and effective maintenance.
			 */
			p3: () => LocalizedString
			/**
			 * AlKholi Trading provides mechanical storage, fixed storage, and automated storage solutions for a range of industries. Our services are designed to maximize efficiency and reduce costs for our clients.
			 */
			p4: () => LocalizedString
		}
		atAlkholi: {
			/**
			 * AT AL KHOLI GROUP
			 */
			title: () => LocalizedString
			/**
			 * What to Anticipate From Us?
			 */
			q1: () => LocalizedString
			/**
			 * At Al Kholi Group, expect a partnership founded on excellence and trust. Here's what to anticipate when collaborating with us:
			 */
			p1: () => LocalizedString
			/**
			 * Professionalism and Expertise: Our team comprises seasoned professionals with a profound understanding and extensive experience in each project, ensuring your needs are 	met with utmost expertise.
			 */
			p2: () => LocalizedString
			/**
			 * Tailored Solutions: Acknowledging our clients' unique requirements, we provide customized solutions meticulously crafted to align with your specific demands, ensuring a precise fit for your project's objectives.
			 */
			p3: () => LocalizedString
			/**
			 * Quality and Efficiency: Our dedication to quality is reflected in our work. We strive to deliver efficient solutions that adhere to your goals while maintaining the highest industry standards.
			 */
			p4: () => LocalizedString
			/**
			 * Transparency and Communication: We value open communication to nurture strong client relationships. Expect complete transparency and ongoing dialogue from our committed team.
			 */
			p5: () => LocalizedString
			/**
			 * Reliability and Trustworthiness: Al Kholi Group is committed to earning your trust and maintaining our reputation as a reliable and trustworthy partner in all business transactions. Choosing Al Kholi Group means selecting a steadfast ally devoted to your success and satisfaction.
			 */
			p6: () => LocalizedString
		}
		projects: {
			/**
			 * our projects
			 */
			title: () => LocalizedString
			/**
			 * Imam University
			 */
			project1Title: () => LocalizedString
			/**
			 * King Fahd Road
			 */
			project2Title: () => LocalizedString
			/**
			 * Abdullah Al Faisal Stadium
			 */
			project3Title: () => LocalizedString
			/**
			 * Was founded in 1953. In 1974, it was granted university status by royal decree.The university houses 10 faculties. It currently has more than 24,000 students and 1,300 faculty.It has intermediate and secondary Islamic institutes in major cities of Saudi Arabia, Indonesia, Djibouti and Japan.
			 */
			project1Paragraph: () => LocalizedString
			/**
			 * King Fahad Road, in the heart of Riyadh city. Our professionals in Maintenance and Operations keeps the long crowded street clean and in a great condition.
			 */
			project2Paragraph: () => LocalizedString
			/**
			 * The stadium is located in the south east of Jeddah, between King Abdulaziz University and the industrial city (Al Waziriah District). The stadium was constructed in 1970, and has a capacity of around 27,000 spectators, and is part of a municipal sports complex that includes an indoor arena and an aquatics center.
			 */
			project3Paragraph: () => LocalizedString
		}
		testimonials: {
			/**
			 * client testimonials
			 */
			title: () => LocalizedString
		}
		companies: {
			/**
			 * OUR Companies
			 */
			title: () => LocalizedString
		}
	}
	divisions: {
		/**
		 * our divisions
		 */
		title: () => LocalizedString
	}
	about: {
		aboutSection: {
			/**
			 * About Us
			 */
			about: () => LocalizedString
			/**
			 * Our History
			 */
			story: () => LocalizedString
			/**
			 * Our Values
			 */
			values: () => LocalizedString
		}
		timeline: {
			/**
			 * Time line
			 */
			title: () => LocalizedString
			/**
			 * As we continue to grow and expand, we remain steadfast in our commitment to excellence. Our timeline reflects our journey towards becoming a leading provider of innovative solutions across a range of industries. From our humble beginnings in the 70s to the present day, we have worked tirelessly to establish ourselves as a trusted partner to our clients and a respected member of the Saudi Arabian business community.
			 */
			p1: () => LocalizedString
		}
		missionVision: {
			/**
			 * Mission
			 */
			missionT: () => LocalizedString
			/**
			 * Empowering informed decisions through excellence and innovative solutions rooted in local market expertise.
			 */
			missionP: () => LocalizedString
			/**
			 * Vision
			 */
			visionT: () => LocalizedString
			/**
			 * To excel in the industry through constant innovation and reinvention.
			 */
			visionP: () => LocalizedString
		}
		chairmanMsg: {
			/**
			 * A legacy built over half a century, the Al Kholi Group has built its reputation in the Kingdom through means of sustainability, quality work delivered on time, and having experts on our team who diligently support each project. From the very beginning, our core focus has been on convenience of our Customers. Throughout the years, our hard work and commitment have resulted in the Al Kholi Group serving as gateway between Saudi Arabia and our international Partners that has allowed us to continue working towards our long term goals through innovation, clear direction, and meticulous organisation.
			 */
			first: () => LocalizedString
			/**
			 * Branching out and setting up subsidiaries that cater to various sectors of Technologies and Healthcare, Construction, Facilities Maintenance, Management Consulting, Energy Retrofit, Elevators and Escalators, and MEP Contracting as well as Pre-Fabrication, we have dedicated ourselves to enhancing the quality of life of our community.
			 */
			second: () => LocalizedString
			/**
			 * Our core success factors are our distinguished management, our diversified portfolio of services, products, Partners and Clients as well as our dedication to the goal of creating a sustainable environment for our employees and customers. We  are working towards a comprehensive approach to sustainability and the environmental safety that will set the precedence for the future. We lay the foundations today and begin the ground work for a better, healthier, and safer today, tomorrow, and the years to come. 
			 */
			third: () => LocalizedString
		}
		team: {
			/**
			 * Meet the team
			 */
			title: () => LocalizedString
		}
		partners: {
			/**
			 * PARTNERS
			 */
			title: () => LocalizedString
			/**
			 * At the Al Kholi Group, we are honored to have established strong partnerships with a range of esteemed organizations across Saudi Arabia. Our key partners include:
			 */
			p1: () => LocalizedString
		}
	}
	companies: {
		/**
		 * Our companies
		 */
		title: () => LocalizedString
		/**
		 * Contact Us
		 */
		contact: () => LocalizedString
		/**
		 * Company Profile
		 */
		profile: () => LocalizedString
		/**
		 * AMOS is a facilities management company that provides a range of services, including specialist hard services, hard services, soft services, and landscaping. We are committed to deliver comprehensive solutions that are tailored to meet the specific needs of each client.
		 */
		amos: () => LocalizedString
		/**
		 * Saudi Building Technique & Maintenance Company is specialized in providing construction, MEP, management services, facility maintenance. SBTMC  is a 100% Saudi Company with a management and workforce of various nationalities. SBTMC provides a full range of specialized services that reflect the upscale and advanced level of design facilities in Saudi Arabia.
		 */
		sbtmc: () => LocalizedString
		/**
		 * UP is a specialized in MEP contracting (mechanical, electrical, and plumbing), maintenance, and facilities maintenance. The company provides a full range of services, including operation and maintenance services, construction, and communication. We have a highly talented team of experts who provide upscale and advanced level design facilities in Saudi Arabia.
		 */
		upmoc: () => LocalizedString
		/**
		 * BTECO provides elevators, escalators, and heavy-duty lifts for a range of industries. Our services are designed to meet the unique requirements of each client, and we are committed to provide high-quality solutions that are efficient and effective.
		 */
		bteco: () => LocalizedString
		/**
		 * AKTEK provides MEP pre-fabrication services on or off-site, delivering innovative solutions that maximize efficiency and reduce costs for our clients.
		 */
		aktek: () => LocalizedString
		/**
		 * AKSTRA is a consulting company that provides experiential learning expertise to deliver long-lasting results for our clients. We combine responsiveness and actionability with a commitment to customizing solutions to fit the unique requirements of each client.
		 */
		akstra: () => LocalizedString
		/**
		 * Technologies is a technology company that helps different industries re-imagine their businesses for the digital age. Our technology partners, products, and services are built with innovation and a focus on client relationships.
		 */
		tech: () => LocalizedString
		/**
		 * AlKholi Trading provides mechanical storage, fixed storage, and automated storage solutions for a range of industries. Our services are designed to maximize efficiency and reduce costs for our clients.
		 */
		trading: () => LocalizedString
		/**
		 * Al Kholi Health Care is a prominent healthcare provider in Saudi Arabia that was founded in 1993. We offer a range of medical and pharmaceutical services and have become highly respected in the industry. We prioritize patient care and employ experienced medical professionals while utilizing the latest technologies and treatments. The company operates multiple clinics and hospitals across the country and is known for delivering quality healthcare services to both local and international patients.
		 */
		hcare: () => LocalizedString
	}
	projects: {
		/**
		 * Our projects
		 */
		title: () => LocalizedString
		/**
		 * All
		 */
		all: () => LocalizedString
		/**
		 * Education
		 */
		education: () => LocalizedString
		/**
		 * Construction
		 */
		construction: () => LocalizedString
		/**
		 * Healthcare
		 */
		healthcare: () => LocalizedString
		/**
		 * Maintenance
		 */
		maintenance: () => LocalizedString
		/**
		 * Government
		 */
		government: () => LocalizedString
	}
	partners: {
		/**
		 * OUR KEY PARTNERS
		 */
		title: () => LocalizedString
		/**
		 * government
		 */
		t1: () => LocalizedString
		/**
		 * foods & beverages
		 */
		t2: () => LocalizedString
	}
	contact: {
		/**
		 * Get
		 */
		title1: () => LocalizedString
		/**
		 * In Touch
		 */
		title2: () => LocalizedString
		/**
		 * Phone
		 */
		phone: () => LocalizedString
		/**
		 * +966114041919
		 */
		phone1: () => LocalizedString
		/**
		 * +966114022426
		 */
		phone2: () => LocalizedString
		/**
		 * location
		 */
		location: () => LocalizedString
		/**
		 * 3821-3847 Zoubaidah Bint Jaafar,
		 */
		addressPart1: () => LocalizedString
		/**
		 * An Murabaa, Riyadh 12613
		 */
		addressPart2: () => LocalizedString
		/**
		 * email
		 */
		email: () => LocalizedString
		/**
		 * info@alkholi.com
		 */
		emailAddress: () => LocalizedString
	}
	form: {
		/**
		 * Full Name*
		 */
		fullName: () => LocalizedString
		/**
		 * Name length should be more than 2 characters!
		 */
		fullNameError: () => LocalizedString
		/**
		 * Name is too long! Maximum 60 characters.
		 */
		fullNameLengthError: () => LocalizedString
		/**
		 * No numbers are allowed!
		 */
		fullNameNumericError: () => LocalizedString
		/**
		 * Your good name ...
		 */
		fullNamePlaceholder: () => LocalizedString
		/**
		 * Please enter a valid email!
		 */
		emailError: () => LocalizedString
		/**
		 * Email Address*
		 */
		emailPlaceholder: () => LocalizedString
		/**
		 * Mobile number (05xxxxxxxx)
		 */
		mobilePlaceholder: () => LocalizedString
		/**
		 * Please enter a valid mobile number!
		 */
		mobileError: () => LocalizedString
		/**
		 * Type Of Project
		 */
		typeOfProject: () => LocalizedString
		/**
		 * Please chose a project type!
		 */
		projectError: () => LocalizedString
		/**
		 * Message*
		 */
		textAreaPlaceholder: () => LocalizedString
		/**
		 * Message is too short!
		 */
		textAreaError1: () => LocalizedString
		/**
		 * Message is too long! Maximum 500 characters.
		 */
		textAreaError2: () => LocalizedString
		/**
		 * Send
		 */
		submit: () => LocalizedString
		/**
		 * Thank You!
		 */
		successFeedback: () => LocalizedString
		/**
		 * Something went wrong!
		 */
		errorFeedback: () => LocalizedString
		/**
		 * I agree to the terms & conditions
		 */
		conditions: () => LocalizedString
	}
	joinUsForm: {
		/**
		 * Want to join our team?
		 */
		title: () => LocalizedString
		/**
		 * Visit Our LinkedIn Page
		 */
		subTitle: () => LocalizedString
		/**
		 * Full Name*
		 */
		fullName: () => LocalizedString
		/**
		 * Name length should be more than 2 characters!
		 */
		fullNameError: () => LocalizedString
		/**
		 * Name is too long! Maximum 60 characters.
		 */
		fullNameLengthError: () => LocalizedString
		/**
		 * No numbers are allowed!
		 */
		fullNameNumericError: () => LocalizedString
		/**
		 * Your good name ...
		 */
		fullNamePlaceholder: () => LocalizedString
		/**
		 * Please enter a valid email!
		 */
		emailError: () => LocalizedString
		/**
		 * Email Address*
		 */
		emailPlaceholder: () => LocalizedString
		/**
		 * Mobile number (05xxxxxxxx)
		 */
		mobilePlaceholder: () => LocalizedString
		/**
		 * Please enter a valid mobile number!
		 */
		mobileError: () => LocalizedString
		/**
		 * Select a position ...
		 */
		positionPlaceholder: () => LocalizedString
		/**
		 * Operations
		 */
		position1: () => LocalizedString
		/**
		 * Sales
		 */
		position2: () => LocalizedString
		/**
		 * Human Resources
		 */
		position3: () => LocalizedString
		/**
		 * Information Technologies
		 */
		position4: () => LocalizedString
		/**
		 * Accountant
		 */
		position5: () => LocalizedString
		/**
		 * Technician
		 */
		position6: () => LocalizedString
		/**
		 * Labor
		 */
		position7: () => LocalizedString
		/**
		 * Other
		 */
		position8: () => LocalizedString
		/**
		 * Attach Your CV ...
		 */
		resumeAttachment: () => LocalizedString
		/**
		 * Type Of Project
		 */
		typeOfProject: () => LocalizedString
		/**
		 * Message*
		 */
		textAreaPlaceholder: () => LocalizedString
		/**
		 * Message is too short!
		 */
		textAreaError1: () => LocalizedString
		/**
		 * Message is too long! Maximum 500 characters.
		 */
		textAreaError2: () => LocalizedString
		/**
		 * Send
		 */
		submit: () => LocalizedString
		/**
		 * Thank You!
		 */
		successFeedback: () => LocalizedString
		/**
		 * Something went wrong!
		 */
		errorFeedback: () => LocalizedString
		/**
		 * I agree to the terms & conditions
		 */
		conditions: () => LocalizedString
	}
}

export type Formatters = {}
