// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * A​l​k​h​o​l​i​ ​G​r​o​u​p
	 */
	title: string
	nav: {
		/**
		 * W​e​l​c​o​m​e​ ​T​o​ ​A​L​K​H​O​L​I
		 */
		welcomeMsg: string
	}
	hero: {
		/**
		 * B​U​I​L​D​.
		 */
		build: string
		/**
		 * O​P​T​I​M​I​Z​E​.
		 */
		optimize: string
		/**
		 * C​O​N​N​E​C​T​.
		 */
		connect: string
		/**
		 * L​e​a​r​n​ ​M​o​r​e
		 */
		more: string
	}
	home: {
		aboutSection: {
			/**
			 * A​b​o​u​t​ ​U​s
			 */
			about: string
			/**
			 * O​u​r​ ​V​i​s​i​o​n
			 */
			vision: string
			/**
			 * O​u​r​ ​M​i​s​s​i​o​n
			 */
			mission: string
		}
	}
	about: {
		aboutSection: {
			/**
			 * A​b​o​u​t​ ​U​s
			 */
			about: string
			/**
			 * O​u​r​ ​H​i​s​t​o​r​y
			 */
			story: string
			/**
			 * O​u​r​ ​V​a​l​u​e​s
			 */
			values: string
		}
	}
	form: {
		/**
		 * N​a​m​e​:
		 */
		fullName: string
		/**
		 * N​a​m​e​ ​l​e​n​g​t​h​ ​s​h​o​u​l​d​ ​b​e​ ​m​o​r​e​ ​t​h​a​n​ ​2​ ​c​h​a​r​a​c​t​e​r​s​!
		 */
		fullNameError: string
		/**
		 * N​a​m​e​ ​i​s​ ​t​o​o​ ​l​o​n​g​!​ ​M​a​x​i​m​u​m​ ​6​0​ ​c​h​a​r​a​c​t​e​r​s​.
		 */
		fullNameLengthError: string
		/**
		 * N​o​ ​n​u​m​b​e​r​s​ ​a​r​e​ ​a​l​l​o​w​e​d​!
		 */
		fullNameNumericError: string
		/**
		 * Y​o​u​r​ ​g​o​o​d​ ​n​a​m​e​ ​.​.​.
		 */
		fullNamePlaceholder: string
		/**
		 * E​m​a​i​l​:
		 */
		email: string
		/**
		 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​a​ ​v​a​l​i​d​ ​e​m​a​i​l​!
		 */
		emailError: string
		/**
		 * E​m​a​i​l​ ​a​d​d​r​e​s​s​ ​.​.​.​ ​(​o​p​t​i​o​n​a​l​)
		 */
		emailPlaceholder: string
		/**
		 * M​o​b​i​l​e​ ​N​u​m​b​e​r​:
		 */
		mobileNumber: string
		/**
		 * M​o​b​i​l​e​ ​n​u​m​b​e​r​ ​(​0​5​x​x​x​x​x​x​x​x​)
		 */
		mobilePlaceholder: string
		/**
		 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​a​ ​v​a​l​i​d​ ​m​o​b​i​l​e​ ​n​u​m​b​e​r​!
		 */
		mobileError: string
		/**
		 * M​e​s​s​a​g​e​:
		 */
		textArea: string
		/**
		 * M​e​s​s​a​g​e​*
		 */
		textAreaPlaceholder: string
		/**
		 * M​e​s​s​a​g​e​ ​i​s​ ​t​o​o​ ​s​h​o​r​t​!
		 */
		textAreaError1: string
		/**
		 * M​e​s​s​a​g​e​ ​i​s​ ​t​o​o​ ​l​o​n​g​!​ ​M​a​x​i​m​u​m​ ​5​0​0​ ​c​h​a​r​a​c​t​e​r​s​.
		 */
		textAreaError2: string
		/**
		 * S​e​n​d​ ​Y​o​u​r​ ​M​e​s​s​a​g​e
		 */
		submit: string
		/**
		 * T​h​a​n​k​ ​Y​o​u​!
		 */
		successFeedback: string
		/**
		 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​!
		 */
		errorFeedback: string
		/**
		 * A​t​ ​l​e​a​s​t​ ​a​n​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​ ​o​r​ ​a​ ​m​o​b​i​l​e​ ​n​u​m​b​e​r​ ​i​s​ ​r​e​q​u​i​r​e​d​!
		 */
		notAllowedFeedback: string
	}
}

export type TranslationFunctions = {
	/**
	 * Alkholi Group
	 */
	title: () => LocalizedString
	nav: {
		/**
		 * Welcome To ALKHOLI
		 */
		welcomeMsg: () => LocalizedString
	}
	hero: {
		/**
		 * BUILD.
		 */
		build: () => LocalizedString
		/**
		 * OPTIMIZE.
		 */
		optimize: () => LocalizedString
		/**
		 * CONNECT.
		 */
		connect: () => LocalizedString
		/**
		 * Learn More
		 */
		more: () => LocalizedString
	}
	home: {
		aboutSection: {
			/**
			 * About Us
			 */
			about: () => LocalizedString
			/**
			 * Our Vision
			 */
			vision: () => LocalizedString
			/**
			 * Our Mission
			 */
			mission: () => LocalizedString
		}
	}
	about: {
		aboutSection: {
			/**
			 * About Us
			 */
			about: () => LocalizedString
			/**
			 * Our History
			 */
			story: () => LocalizedString
			/**
			 * Our Values
			 */
			values: () => LocalizedString
		}
	}
	form: {
		/**
		 * Name:
		 */
		fullName: () => LocalizedString
		/**
		 * Name length should be more than 2 characters!
		 */
		fullNameError: () => LocalizedString
		/**
		 * Name is too long! Maximum 60 characters.
		 */
		fullNameLengthError: () => LocalizedString
		/**
		 * No numbers are allowed!
		 */
		fullNameNumericError: () => LocalizedString
		/**
		 * Your good name ...
		 */
		fullNamePlaceholder: () => LocalizedString
		/**
		 * Email:
		 */
		email: () => LocalizedString
		/**
		 * Please enter a valid email!
		 */
		emailError: () => LocalizedString
		/**
		 * Email address ... (optional)
		 */
		emailPlaceholder: () => LocalizedString
		/**
		 * Mobile Number:
		 */
		mobileNumber: () => LocalizedString
		/**
		 * Mobile number (05xxxxxxxx)
		 */
		mobilePlaceholder: () => LocalizedString
		/**
		 * Please enter a valid mobile number!
		 */
		mobileError: () => LocalizedString
		/**
		 * Message:
		 */
		textArea: () => LocalizedString
		/**
		 * Message*
		 */
		textAreaPlaceholder: () => LocalizedString
		/**
		 * Message is too short!
		 */
		textAreaError1: () => LocalizedString
		/**
		 * Message is too long! Maximum 500 characters.
		 */
		textAreaError2: () => LocalizedString
		/**
		 * Send Your Message
		 */
		submit: () => LocalizedString
		/**
		 * Thank You!
		 */
		successFeedback: () => LocalizedString
		/**
		 * Something went wrong!
		 */
		errorFeedback: () => LocalizedString
		/**
		 * At least an email address or a mobile number is required!
		 */
		notAllowedFeedback: () => LocalizedString
	}
}

export type Formatters = {}
